package mygradle;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'syono' at '16. 10. 8 오후 2:51' with Gradle 3.0
 *
 * @author syono, @date 16. 10. 8 오후 2:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
