package mygradle;

import mygradle.Library;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'syono' at '16. 10. 8 오후 2:51' with Gradle 3.0
 *
 * @author syono, @date 16. 10. 8 오후 2:51
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
